# Generated by Django 4.2.6 on 2023-10-06 05:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=100, null=True)),
                ('white', models.CharField(blank=True, max_length=100, null=True)),
                ('black', models.CharField(blank=True, max_length=100, null=True)),
                ('outcome', models.CharField(blank=True, max_length=100, null=True)),
                ('fen', models.CharField(help_text='Most recent FEN.', max_length=100)),
                ('pgn', models.TextField(blank=True, help_text='PGN of game.', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ply', models.IntegerField(help_text='Half-play count (even = white, odd = black).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('uci', models.CharField(help_text='Universal Chess Interface.', max_length=10)),
                ('san', models.CharField(help_text='Standard Algebraic Notation.', max_length=10)),
                ('fen', models.CharField(help_text='FEN prior to move.', max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessgpt.game')),
            ],
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('function', 'Function'), ('system', 'System'), ('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('fname', models.CharField(max_length=30, null=True)),
                ('content', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessgpt.game')),
            ],
        ),
    ]
