# Generated by Django 4.2.5 on 2023-10-05 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Event name', max_length=200, null=True)),
                ('result', models.IntegerField(choices=[(1, '1-0'), (2, '0-1'), (3, '1/2-1/2')], help_text='Game result', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('timeControl', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.CharField(choices=[('K', 'king'), ('Q', 'queen'), ('R', 'rook'), ('B', 'bishop'), ('N', 'knight'), ('', 'pawn')], max_length=1)),
                ('capture', models.BooleanField(default=False)),
                ('source', models.CharField(max_length=2)),
                ('destination', models.CharField(max_length=2)),
                ('checkType', models.CharField(blank=True, choices=[('+', 'check'), ('#', 'checkmate')], max_length=1, null=True)),
                ('promotion', models.CharField(blank=True, choices=[('K', 'king'), ('Q', 'queen'), ('R', 'rook'), ('B', 'bishop'), ('N', 'knight'), ('', 'pawn')], max_length=1, null=True)),
                ('castle', models.CharField(blank=True, choices=[('O-O', 'kingside'), ('O-O-O', 'queenside')], max_length=5, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.IntegerField(choices=[(1, 'white'), (2, 'black')])),
                ('elapsed', models.IntegerField(default=0, help_text='Time elapsed in seconds')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessgpt.game')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'system'), (2, 'user'), (3, 'assistant')])),
                ('content', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessgpt.game')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
