# Generated by Django 4.2.5 on 2023-10-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessgpt', '0002_remove_game_timecontrol_alter_game_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['id']},
        ),
    ]
