# Generated by Django 4.2.6 on 2023-10-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessgpt', '0003_alter_game_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='fname',
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='role',
            field=models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant')], max_length=10),
        ),
    ]
