# Generated by Django 4.2.6 on 2023-10-15 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessgpt', '0004_remove_chathistory_fname_alter_chathistory_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='turn',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='ply',
            field=models.IntegerField(help_text='Half-play count (even = white, odd = black).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
        ),
    ]
