# Generated by Django 4.2.6 on 2023-10-15 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessgpt', '0005_move_turn_alter_move_ply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='turn',
        ),
        migrations.AddField(
            model_name='move',
            name='outcome',
            field=models.CharField(blank=True, default='', help_text='Outcome of this move, if any.', max_length=100),
        ),
        migrations.AlterField(
            model_name='move',
            name='ply',
            field=models.IntegerField(help_text='Half-play count (even = white, odd = black).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
    ]
